services:
  db:
    image: postgres:latest
    container_name: air_tashkent_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airtashkent
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/data:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Expose port 80 from the container to 3000 on the host
    env_file:
      - ./frontend/.env
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" # Expose port 8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
