"""Migrate to PostgreSQL schema

Revision ID: 61e8d112896b
Revises: 9b52cc318ec1
Create Date: 2024-12-16 23:21:21.871236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e8d112896b'
down_revision: Union[str, None] = '9b52cc318ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
