"""Added parameter name and parameters

Revision ID: 7656148fe268
Revises: 0e5e1030d2a9
Create Date: 2024-12-06 16:44:00.473945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7656148fe268'
down_revision: Union[str, None] = '0e5e1030d2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_name',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter',
    sa.Column('well', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_name'], ['parameter_name.id'], ),
    sa.ForeignKeyConstraint(['well'], ['geo_well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter')
    op.drop_table('parameter_name')
    # ### end Alembic commands ###
